name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Build
        run: |
          npm install
          npm run build
      # docs must come first, tests write to a sub dir
      - name: Build docs
        run: npm run build-docs
      - name: Lint
        run: npm run lint
      - name: Tests
        run: npm test
      - name: Prepare Documentation Site
        run: |
          mkdir ./site
          cp -r ./docs ./site/docs
          cp -r ./dist/* ./site
          cp ./site/index.html ./site/404.html
      - name: Publish Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./site
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Publish NPM Module
        uses: JS-DevTools/npm-publish@v1
        with:
          check-version: false
          token: ${{ secrets.NPM_DEPLOY_KEY }}
